plugins {
    id 'java-library'
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.141'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

file("../gradle.properties").withInputStream {
    def props = new Properties()
    props.load(it)
    props.each { prop -> project.ext.set(prop.key, prop.value) }
}

version = mod_version
group = mod_group

base {
    archivesName = "${mod_name}-${minecraft_version}-neoforge"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

eclipse {
    project { name = "${mod_name}-${minecraft_version}-neoforge" }
}

neoForge {
    version = neo_version

    accessTransformers = ['src/main/resources/META-INF/accesstransformer.cfg']

    runs {
        client {
            client()
            gameDirectory = project.file('../run')
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
        server {
            server()
            gameDirectory = project.file('../run')
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
    }

    mods {
        musketmod {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.java { srcDir '../src/main/java' }
sourceSets.main.resources { srcDir '../src/main/resources' }

repositories {
    maven { url "https://maven.shedaniel.me/" }
}

dependencies {
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
        mod_version: mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
